### ISSUE TITLE
Nuake is not persistent during buffer switch

### ISSUE THREAD

**Issue by nabaco** [Lenovsky/nuake#10]
**Steps to reproduce:**
- Open buffer
- Open Nuake and do operations
- Close Nuake and switch buffer
- Open Nuake and see a new instance instead of the old one

Nuake is persistent between tabs.

Installed on Neovim

**Comment by lenowski** [comment]
I can't reproduce that, for me, it's always the same Nuake instance. Have you tried to test with some kind of minimal configuration?

Edit: After further analysis, I can confirm that there's a problem with persistent - I'm working on fixing this.
